### ISSUE TITLE
Cards cannot be added as TexturedBoxes to the screen.

### ISSUE THREAD

**Issue by Dylan-Brisco** [hjarrell/chaotic-card#22]
After creating a new card object and calling card.draw(), the card image was not added to the screen.

**Comment by hjarrell** [comment]
@Dylan-Brisco Did you give it a location?

**Comment by hjarrell** [comment]
You can use card.move(x,y) to change its location

**Comment by Dylan-Brisco** [comment]
Yea, I wrote

 c = Card.QUEEN_OF_HEARTS;
        c.move(DisplayManager.HEIGHT/4,DisplayManager.WIDTH/2);
        c.draw();

**Comment by Dylan-Brisco** [comment]
c.draw was called in the Draw method, but it still won't appear on the screen.

**Comment by hjarrell** [comment]
@Dylan-Brisco The card was not being given a size component. Use the setSizeAndLocation method to fix this.
