### ISSUE TITLE
Need to create the screens for the game.

### ISSUE THREAD

**Issue by hjarrell** [hjarrell/chaotic-card#55]
All of these need to be implemented.

- [x] Main Menu
- [x] Enter IP and Nickname
- [ ] Lobby
- [x] BS Game Window
- [x] Difungo Game Window
- [x] Disconnected Window

**Comment by hjarrell** [comment]
Finished main menu

**Comment by Dylan-Brisco** [comment]
Created BS menu

**Comment by Dylan-Brisco** [comment]
Created Difungo window

**Comment by Dylan-Brisco** [comment]
Created the Disconnected Menu

**Comment by hjarrell** [comment]
Lobby will no longer be needed
